sudo: required
services:
  - docker
language: python
python:
  - 3.6
jobs:
  include:
    - stage: "build"
      script:
        - sh ./.makefile/start.sh
    - stage: "test"
      script:
        - pwd
        - ls -la
        - python manage.py test users
    - stage: "deploy"
      if: branch = master
      script:
        - echo deployment
after_success:
  - echo "Success"