version: '3'

services:
  app:
    build:
      context: .
      args:
        USER_ID: $USER_ID
    env_file:
      - app.env
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"
    depends_on:
      - db_postgres
      - redis

  db_postgres:
    image: postgres

  redis:
    image: redis